# Generated by Django 4.2 on 2023-04-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='bookings_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество бронирований'),
        ),
    ]
