# Generated by Django 4.2 on 2023-04-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
